#!/bin/bash
apt-get update -y; apt-get upgrade -y; apt-get dist-upgrade -y; apt-get autoremove -y
apt-get install build-essential libssl-dev curl nano wget zip unzip git lsof iftop htop vim ffmpeg -y
apt-get install -y ca-certificates apt-transport-https lsb-release 

apt-get install -y man-db make m4 netcat-openbsd odbcinst1debian2 patch
apt-get install -y pkg-config python2 python2-minimal python2.7 python2.7-minimal re2c unixodbc unixodbc-dev
apt-get install -y uuid-dev x11-common x11proto-core-dev x11proto-input-dev x11proto-kb-dev libgeoip-dev
apt-get install -y po-debconf xorg-sgml-doctools xtrans-dev zlib1g-dev libjpeg-dev libgcc1 libgd-dev
apt-get install -y libgtk2.0-0 libgdk-pixbuf2.0-0 libfontconfig1 libxrender1 libx11-6 libglib2.0-0  libxft2 libfreetype6 libc6 zlib1g libpng-dev

wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list
apt update

apt install -y php8.0 php8.0-cgi php8.0-bcmath php8.0-bz2 php8.0-cli php8.0-common php8.0-curl php8.0-dba php8.0-dev php8.0-enchant php8.0-fpm php8.0-gd php8.0-gmp php8.0-imap php8.0-interbase php8.0-intl php8.0-ldap php8.0-mbstring php8.0-mysql php8.0-odbc php8.0-opcache php8.0-pgsql php8.0-phpdbg php8.0-pspell php8.0-readline  php8.0-snmp php8.0-soap php8.0-sqlite3 php8.0-sybase php8.0-tidy php8.0-xml php8.0-xmlrpc php8.0-xsl php8.0-zip

